name: Create discussion

on:
  workflow_dispatch:
jobs:
  createDiscussion:
    runs-on: ubuntu-latest
    steps:
      - name: Create Discussion
        env: 
          graphql_endpoint: "https://api.github.com/graphql"
          graphql_script: |
                        mutation { 
                           createDiscussion(input: {repositoryId: "MDEwOlJlcG9zaXRvcnkxNTI2NjY4MDA=", categoryId: "MDEwOkRpc2N1c3Npb24zNDEyMTcy", body: "The body", title: "The title"}) { 
                                  discussion { 
                                    id 
                                  } 
                                } 
                              }        
        run: |
          graphql_script="$(echo ${graphql_script//\"/\\\"})"
          echo $graphql_script
          curl -ksS \
          -H 'authorization: Bearer ${{ secrets.USER_TOKEN }}' \
          -H 'Content-Type: application/json' \
          -d "{ \"query\": \"$graphql_script\"}" \
          $graphql_endpoint | jq .
